### ISSUE TITLE
[1.16.5] Pipez dropping tps on server

### ISSUE THREAD

**Issue by YOYOK9** [henkelmax/pipez#22]
**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
On my server as more people use the pipez mod tps begins to drop. I have run a spark profiler and the highest use points to UpdateTimeLightAndEntities which then goes into pipezs. From my client side testing I dont see any issue, however, I cant do all the crazy stuff people are doing on my server on the client (range and what not) 

**Expected behavior**
Tps/server performance hold steady. 

**Log files**
Please provide log files of the game session in which the problem occurred.
Profiler: https://spark.lucko.me/hteRQpkMMi
Servers LatestLog: https://gist.github.com/YOYOK9/11ceaf0615e8fecc8a5f7231165408ad
**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.4
- Mod version: pipez-1.16.5-1.2.1

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
Servers mod list: https://pastebin.com/x4w0DBme

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/113763768-5c650400-971a-11eb-9c90-4d867cf4d646.png)

From your profiler it looks like there are many pipes connected to iron furnaces or something. Since the percentage of lag produced by the pipes in relation to the furnaces seems normal.

These pipes don't magically remove all lag. They are pretty efficient, but if you have a ton of stuff, eventually, it will lag the server. The pipes are coded in such a way that they create zero lag on the client, but the logic still takes resources on the server and that's perfectly normal.

**Comment by YOYOK9** [comment]
ah ok, and looking at your picture I know exactly who the issue is from... Is there any options you would recommend that could help with this?  Other then lower the number of pipes connected to the furnaces

**Comment by henkelmax** [comment]
Youncan play around with the sorting modes a little bit. Round robin is sometimes a little more intensive... Maybe try setting the pipes to nearest first.
