### ISSUE TITLE
Allow for bi-directional pipe interfaces

### ISSUE THREAD

**Issue by TheDarkFlame** [henkelmax/pipez#34]
it is currently not possible to both insert and extract from the same pipe interface

for some machines it would be useful to specify both insertion and extraction, and for the universal pipez, perhaps be able to specify it per-type (item,gas,fluid,energy)

I think it makes the most sense if the default is to not insert, but insertion into an extraction pipe should be able to be forced by using the Filter Destination Tool.

an example of where this might be handy is:
the Fired Crucible from Ex Nihilo: Sequentia accepts cobble and transforms it into lava, I'd love to have a single connector to insert cobble and extract lava instead of one connector for insertion and another for extraction. (would enable making designs SIGNIFICANTLY more compact)

**Comment by henkelmax** [comment]
I already considered that, but the problem is that it would introduce a lot of strange behaviors. If you for example would be doing that for chests, it would insert and extract at the same time into the container, this may lead to strange behaviors in the container and would cause unnecessary lag. So I decided against it in favor of just attaching a second wire to the block.

**Comment by DDzwiedziu** [comment]
If it's of any help Ender IO solved this by having an option to allow or not self-feeding at the connection.
