### ISSUE TITLE
Energy Pipe not pulling energy from Bigger Reactor

### ISSUE THREAD

**Issue by gster617** [henkelmax/pipez#6]
Just wanted to start by saying thank you for your time and response! :)

**Please read the [FAQ](https://modrepo.de/minecraft/pipez/faq) before submitting a bug report!**

**Bug description**
Cannot pull power from Bigger Reactors Reactor Power Tap (I am able to pull the power using cables from other mods)

**Steps to reproduce the issue**
1. Create a Bigger Reactors Reactor that is generating power
2. Attach a Pipez Energy Pipe to the Bigger Reactors Reactor Power Tap
3. Use the Pipez Pipe Wrench to set the pipe to extract
4. Connect the other end of the energy pipe to any power accepting block (ex. empty Mekanism Energy Cube)

**Expected behavior**
Should pull power from Bigger Reactors Reactor Power Tap and put into power accepting blocks

**Log files**
https://gist.github.com/gster617/11c354f33b8987bbb6e5cbde3702e48f.js

**Versions**
- Minecraft version
- 1.16.5

- Modpack
- All the Mods 6 To the Sky
- 1.0.1

- Forge version
- 36.0.46

- Mod version
- Pipez 1.1.2

**Other mods**
- Bigger Reactors 0.4.3

**Screenshots**
![2021-03-10_14 25 10](https://user-images.githubusercontent.com/80423093/110689298-89bca180-81b0-11eb-833d-b9786779c4d5.png)
![2021-03-10_14 25 21](https://user-images.githubusercontent.com/80423093/110689303-8b866500-81b0-11eb-9e8e-db23accb832d.png)
![2021-03-10_14 25 53](https://user-images.githubusercontent.com/80423093/110689313-8cb79200-81b0-11eb-8f5b-a8b0b9721b24.png)

**Comment by henkelmax** [comment]
> Log files
https://gist.github.com/gster617/11c354f33b8987bbb6e5cbde3702e48f.js

I don't know what you sent there, but it's definitely not your logs.

**Comment by henkelmax** [comment]
This is actually an issue by the Bigger Reactors mod.
They only push energy to cables and don't allow the energy to get pulled.
Because our pipes don't have an energy handler they won't receive energy.

https://github.com/BiggerSeries/BiggerReactors/blob/19052548b9e0b70c0ef5292c8aedff94a60fae7d/src/main/java/net/roguelogix/biggerreactors/classic/reactor/tiles/ReactorPowerTapTile.java#L56-L74

Please report this to their issue tracker.

I am currently working on a fix that if the pipes are connected to the tap, it gets green. But the actual energy transferring issue is their fault.
A workaround would be to put any kind of energy storage block in front of the tap and then connecting it with a pipe.

**Comment by RogueLogix** [comment]
Ill be fixing this in BiR 0.5, however, this should also be fixed in pipez by allowing energy to be pushed in
